//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RGlobal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXWebMRCS.Language.RGlobal", typeof(RGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRCS youth training center is located 68 km away from Ulaanbaatar city, near the iconic Tsonjinboldog Chinggis Khan statue..
        /// </summary>
        public static string camp_p {
            get {
                return ResourceManager.GetString("camp_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRCS YOUTH TRAINING CENTER.
        /// </summary>
        public static string camp_t {
            get {
                return ResourceManager.GetString("camp_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN.
        /// </summary>
        public static string join {
            get {
                return ResourceManager.GetString("join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICRC.
        /// </summary>
        public static string l1 {
            get {
                return ResourceManager.GetString("l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l10.
        /// </summary>
        public static string l10 {
            get {
                return ResourceManager.GetString("l10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRCS timeline.
        /// </summary>
        public static string l2 {
            get {
                return ResourceManager.GetString("l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l3.
        /// </summary>
        public static string l3 {
            get {
                return ResourceManager.GetString("l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l4.
        /// </summary>
        public static string l4 {
            get {
                return ResourceManager.GetString("l4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l5.
        /// </summary>
        public static string l5 {
            get {
                return ResourceManager.GetString("l5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l6.
        /// </summary>
        public static string l6 {
            get {
                return ResourceManager.GetString("l6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l7.
        /// </summary>
        public static string l7 {
            get {
                return ResourceManager.GetString("l7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l8.
        /// </summary>
        public static string l8 {
            get {
                return ResourceManager.GetString("l8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string l9 {
            get {
                return ResourceManager.GetString("l9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        public static string Mongolia {
            get {
                return ResourceManager.GetString("Mongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p1.
        /// </summary>
        public static string p1 {
            get {
                return ResourceManager.GetString("p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p1_t.
        /// </summary>
        public static string p1_t {
            get {
                return ResourceManager.GetString("p1_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can be only one Red Cross or one Red Crescent Society in any one country. It must be open to all. It must carry on its humanitarian work throughout its territory..
        /// </summary>
        public static string p10 {
            get {
                return ResourceManager.GetString("p10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The International Red Cross and Red Crescent Movement, in which all Societies have equal status and share equal responsibilities and duties in helping each other, is worldwide..
        /// </summary>
        public static string p11 {
            get {
                return ResourceManager.GetString("p11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to satisfy the following criterias to become of the MRCS’s 14.800 volunteers:
        ///Criterias:
        ///• Be able to dedicate your time and effort to the welfare of others, with a sincere desire to help others with humility and compassion; • Anyone can become a Mongolian Red Cross Society volunteer without being subject to discrimination on the basis of race, religion, age, or gender..
        /// </summary>
        public static string p12 {
            get {
                return ResourceManager.GetString("p12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string p13 {
            get {
                return ResourceManager.GetString("p13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p14.
        /// </summary>
        public static string p14 {
            get {
                return ResourceManager.GetString("p14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p15.
        /// </summary>
        public static string p15 {
            get {
                return ResourceManager.GetString("p15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p2.
        /// </summary>
        public static string p2 {
            get {
                return ResourceManager.GetString("p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p2_t.
        /// </summary>
        public static string p2_t {
            get {
                return ResourceManager.GetString("p2_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p3.
        /// </summary>
        public static string p3 {
            get {
                return ResourceManager.GetString("p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p3_t.
        /// </summary>
        public static string p3_t {
            get {
                return ResourceManager.GetString("p3_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string p4 {
            get {
                return ResourceManager.GetString("p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The International Red Cross and Red Crescent Movement, born of a desire to bring assistance without discrimination to the wounded on the battlefield, endeavours, in its international and national capacity, to prevent and alleviate human suffering wherever it may be found. Its purpose is to protect life and health and to ensure respect for the human being. It promotes mutual understanding, friendship, cooperation and lasting peace amongst all peoples..
        /// </summary>
        public static string p5 {
            get {
                return ResourceManager.GetString("p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It makes no discrimination as to nationality, race, religious beliefs, class or political opinions. It endeavours to relieve the suffering of individuals, being guided solely by their needs, and to give priority to the most urgent cases of distress..
        /// </summary>
        public static string p6 {
            get {
                return ResourceManager.GetString("p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue to enjoy the confidence of all, the Movement may not take sides in hostilities or engage at any time in controversies of a political, racial, religious or ideological nature..
        /// </summary>
        public static string p7 {
            get {
                return ResourceManager.GetString("p7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Movement is independent. The National Societies, while auxiliaries in the humanitarian services of their governments and subject to the laws of their respective countries, must always maintain their autonomy so that they may be able at all times to act in accordance with the principles of the Movement..
        /// </summary>
        public static string p8 {
            get {
                return ResourceManager.GetString("p8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a voluntary relief movement not prompted in any manner by desire for gain..
        /// </summary>
        public static string p9 {
            get {
                return ResourceManager.GetString("p9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a member.
        /// </summary>
        public static string r1_1_h1 {
            get {
                return ResourceManager.GetString("r1_1_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to become a blood donor.
        /// </summary>
        public static string r1_1_h2 {
            get {
                return ResourceManager.GetString("r1_1_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial first aid training.
        /// </summary>
        public static string r1_1_h3 {
            get {
                return ResourceManager.GetString("r1_1_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string r1_1_h4 {
            get {
                return ResourceManager.GetString("r1_1_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As one of the 249,770 members and supporters of the Mongolian Red Cross Society, you will be able to contribute to humanitarian activities and receive various training for self-development, and build capacity for disaster prevention, preparedness, health care, first aid and psychological support..
        /// </summary>
        public static string r1_1_p1 {
            get {
                return ResourceManager.GetString("r1_1_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In accordance with the Mongolian Law on Blood Donation, the MRCS is responsible for disseminating and attracting blood donors and providing them with training. Based on this obligation, the MRCS promotes the importance of blood donation, disseminates information on the benefits of becoming a blood donor to the public and works to increase the number of active blood donors..
        /// </summary>
        public static string r1_1_p2 {
            get {
                return ResourceManager.GetString("r1_1_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone could be affected by the situations of sudden accident or disease anytime and need for first aid. By obtaining the knowledge and skills of first aid, you will be capable of saving your or your loved ones’ lives..
        /// </summary>
        public static string r1_1_p3 {
            get {
                return ResourceManager.GetString("r1_1_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRCS building, Peace street, Sukhbaatar district, Ulaanbaatar, Mongolia
        ///info@redcross.mn (+976)-11-323334.
        /// </summary>
        public static string r1_1_p4 {
            get {
                return ResourceManager.GetString("r1_1_p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r2_1_1_h1.
        /// </summary>
        public static string r2_1_1_h1 {
            get {
                return ResourceManager.GetString("r2_1_1_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r2_1_h1.
        /// </summary>
        public static string r2_1_h1 {
            get {
                return ResourceManager.GetString("r2_1_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r2_1_p1.
        /// </summary>
        public static string r2_1_p1 {
            get {
                return ResourceManager.GetString("r2_1_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r2_2_1_h1.
        /// </summary>
        public static string r2_2_1_h1 {
            get {
                return ResourceManager.GetString("r2_2_1_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r2_2_1_h2.
        /// </summary>
        public static string r2_2_1_h2 {
            get {
                return ResourceManager.GetString("r2_2_1_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read more....
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string t1_1 {
            get {
                return ResourceManager.GetString("t1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independence.
        /// </summary>
        public static string t10 {
            get {
                return ResourceManager.GetString("t10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voluntary service.
        /// </summary>
        public static string t11 {
            get {
                return ResourceManager.GetString("t11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity.
        /// </summary>
        public static string t12 {
            get {
                return ResourceManager.GetString("t12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universality.
        /// </summary>
        public static string t13 {
            get {
                return ResourceManager.GetString("t13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string t14 {
            get {
                return ResourceManager.GetString("t14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to training.
        /// </summary>
        public static string t14_1 {
            get {
                return ResourceManager.GetString("t14_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BECOME A VOLUNTEER.
        /// </summary>
        public static string t15 {
            get {
                return ResourceManager.GetString("t15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string t16 {
            get {
                return ResourceManager.GetString("t16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string t16_1 {
            get {
                return ResourceManager.GetString("t16_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IS MRCS YOU.
        /// </summary>
        public static string t17 {
            get {
                return ResourceManager.GetString("t17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity .
        /// </summary>
        public static string t18 {
            get {
                return ResourceManager.GetString("t18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        public static string t18_1 {
            get {
                return ResourceManager.GetString("t18_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t19.
        /// </summary>
        public static string t19 {
            get {
                return ResourceManager.GetString("t19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t19_1.
        /// </summary>
        public static string t19_1 {
            get {
                return ResourceManager.GetString("t19_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISASTER .
        /// </summary>
        public static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGEMENT PROGRAM.
        /// </summary>
        public static string t2_1 {
            get {
                return ResourceManager.GetString("t2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPCOMING.
        /// </summary>
        public static string t20 {
            get {
                return ResourceManager.GetString("t20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENTS.
        /// </summary>
        public static string t20_1 {
            get {
                return ResourceManager.GetString("t20_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIAL INCLUSION, .
        /// </summary>
        public static string t21 {
            get {
                return ResourceManager.GetString("t21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOPMENT PROGRAM.
        /// </summary>
        public static string t21_1 {
            get {
                return ResourceManager.GetString("t21_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLIC HEALTH PROMOTION.
        /// </summary>
        public static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAM.
        /// </summary>
        public static string t3_1 {
            get {
                return ResourceManager.GetString("t3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RED CROSS YOUTH .
        /// </summary>
        public static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAM.
        /// </summary>
        public static string t4_1 {
            get {
                return ResourceManager.GetString("t4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONGOING.
        /// </summary>
        public static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECTS.
        /// </summary>
        public static string t5_1 {
            get {
                return ResourceManager.GetString("t5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The seven .
        /// </summary>
        public static string t6 {
            get {
                return ResourceManager.GetString("t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundamental Principles.
        /// </summary>
        public static string t6_1 {
            get {
                return ResourceManager.GetString("t6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanity.
        /// </summary>
        public static string t7 {
            get {
                return ResourceManager.GetString("t7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impartiality.
        /// </summary>
        public static string t8 {
            get {
                return ResourceManager.GetString("t8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutrality.
        /// </summary>
        public static string t9 {
            get {
                return ResourceManager.GetString("t9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid-level branches.
        /// </summary>
        public static string too1 {
            get {
                return ResourceManager.GetString("too1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trained volunteers.
        /// </summary>
        public static string too2 {
            get {
                return ResourceManager.GetString("too2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Cross Youth member.
        /// </summary>
        public static string too3 {
            get {
                return ResourceManager.GetString("too3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanitarian member organizations.
        /// </summary>
        public static string too4 {
            get {
                return ResourceManager.GetString("too4", resourceCulture);
            }
        }
    }
}
